### ISSUE TITLE
Upgrading cache action to the recent version

### ISSUE THREAD

**Issue by abunashir** [metanorma/metanorma-build-scripts#51]
Hi there, Recently while I was working on the CLI then I came across an issue related to the caching gems, and I suspect this might be related to an old version for cache action. Especially even after changing the `*.gemspec` file, it's was using the old hash key.

I temporarily updated it to `cache@v2` in the CLI and it seems to be fixing the issue for now, What do you guys think about updating the cache action version globally here?

Ref: https://github.com/metanorma/metanorma-cli/pull/180

// cc: @CAMOBAP, @ronaldtse

**Comment by ronaldtse** [comment]
@abunashir updating to `cache@v2` sounds fine with me. @CAMOBAP what do you think?

**Comment by CAMOBAP** [comment]
Sounds good to me too, BTW @abunashir could you please post here links to CI runs which used outdated gems, to make sure that the issue was fixed by v2 exactly (not just because cache invalidation)

**Comment by abunashir** [comment]
@CAMOBAP: You are right, I think the issue was mainly because of not invalidating the old cache, not necessarily for version 1. Eg: I changed the gemspec in this PR and I was expecting it to invalidate the old cache but for some reason, it was still failing  - https://github.com/metanorma/metanorma-cli/pull/187  

But I do think there are some advantages of using `v2`, and for some reason, it did fix the issue for now, here are some context: [action/caches@v2](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache). Since you are the master with CIMS, would you mind taking care of this? 😍
